# Generated by Django 3.0.8 on 2020-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200731_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='prfole_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
